### ISSUE TITLE
Bug: Missing file in multi-convert

### ISSUE THREAD

**Issue by ximenesuk** [BritishGeologicalSurvey/AGS-Validator#15]
_Aside: did you know that a task in an issue can be used to create a separate issue automatically?_

What appears to be happening locally is that the CLI converter will convert any `.ags` file into an `.xlxs` file even if that file is not valid. The converse isn't true. So in the bulk convert, the files:
```
dummy.xlsx
empty.ags
example1.ags
example1.xlsx
nonsense.ags      
random_binary.ags
```
will convert to:
```
conversion.log
empty.xlsx
example1.ags
example1.xlsx
nonsense.xlsx
random_binary.xlsx
```
All but the `example1.xlsx` are unreadable.

I think this is a feature to produce an XLSX file for an invalid AGS file for editing and reconversion back. However, our bad AGS files are all really bad with nothing, nonsense or binary in them. The converter should probably fail for fatally bad AGS files - so a bug for them? But for us we may be able to use the log message to delete bad XLSX files, though I am concerned this might delete more aggressively than needed.

**Comment by ximenesuk** [comment]
This branch (on my JSON branch) https://github.com/BritishGeologicalSurvey/AGS-Validator/tree/corrupt-files fixes the problem or corrupt XLSX files. This doesn't prevent non-standard, but parseable, AGS files being converted.

**Comment by ximenesuk** [comment]
On a more general comment. Converting AGS to XLSX and then back to AGS cleans up trivial errors such as line breaks. It could function as a first-pass fix just to clear up the logs for more systematic analysis. But this does raise an issue. Should the log for a successful conversion also detail and standards issues? I.e. to enable the issues to be fixed in the XLSX before reconversion?

A nice example if to look at the five smallest real files:
```
 161-41.ags
 'Mount Severn- Environment Agency.ags'
'Ashfield Area C Development.ags'
Ings_Lane_Immingham.ags
'wells relief bh.ags'
```
 - validate and capture log
 - convert to XLSX
 - convert back to AGS
 - validate and capture log

**Comment by ximenesuk** [comment]
I've opened an issue on the [ags-python-library repo](https://gitlab.com/ags-data-format-wg/ags-python-library/-/issues/21)

**Comment by ximenesuk** [comment]
A useful test here is that:
```
$ touch empty.ags
$ ags4_cli convert empty.ags empty_ags.xlsx
Opening file... empty.ags
Exporting data to... empty_ags.xlsx

Traceback (most recent call last):
...
IndexError: At least one sheet must be visible
```
will produce an XLSX file while converting the same empty file via the API should produce a zip with no XLSX file, just a log.

It would also be worth checking that multiple file produce expected results: the log should match up with the returned files.

**Comment by volcan01010** [comment]
Fixed in https://github.com/BritishGeologicalSurvey/AGS-Validator/pull/19
