### ISSUE TITLE
Provide line number and character when "valid" AGS files fails for UnicodeDecodeError

### ISSUE THREAD

**Issue by ximenesuk** [BritishGeologicalSurvey/AGS-Validator#16]

**Comment by ximenesuk** [comment]
This commit #closes this issue 5dffd1e09a98d69a061ef046e2d616fbed4025f6

Note that the same file provides a different error in the convert function.

**Comment by ximenesuk** [comment]
To test this validate the file `test/files/real/CG014058_F.ags`, this should give the output:
```
File Name: 	 CG014058_F.ags
File Size: 	 49 kB
Time (UTC): 	 2021-08-19 11:34:36

ERROR: Unreadable character on line: 263
Starting: "WS2","0.100","1","D","1","0.100","26.63","75.00","23.00","","","","90.27","425
```
The line where the error occurs is printed upto (but not including) the problem character. This should also work for files where the first character is unreadable, though the message is less useful.

The tests should pass (one added, one modified)

**Comment by volcan01010** [comment]
This is really nice!

I've just had a look at all the non-ASCII encodings for the files that we have:

```bash
$ find test/files/real/ -exec file {} | grep -v ASCII /tmp/encodings.txt | cut -d : -f 2 | sort | uniq
 ISO-8859 text
 ISO-8859 text, with very long lines
 UTF-8 Unicode text
 UTF-8 Unicode text, with very long lines
 UTF-8 Unicode (with BOM) text, with very long lines
```

That looks like ISO-8859 is the only tricky one that we are likely to encounter.  Python 3 is Unicode by default.  I know that Jenn has had issues with BOMs before.

I tried the library and our code against `Blackburn Southern Bypass.ags` and it all works fine.  I've added a test to confirm this.

**Comment by volcan01010** [comment]
I had expected to find some strange Windows encodings in there, but didn't.  If we come across any we can add them to the test suite.

**Comment by volcan01010** [comment]
Closed in https://github.com/BritishGeologicalSurvey/AGS-Validator/pull/19
